from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict

import argparse
import json
import os

import cv2
import numpy as np
import pandas as pd


# ============================================================
# STAMPEDE DETECTION V3.4
# ============================================================
#
# Single-file pipeline:
#
# Video
#   ↓
# YOLOv8 Head Detection
#   ↓
# BoT-SORT Tracking
#   ↓
# Speed / Acceleration / Direction
#   ↓
# Rapid Motion
#   ↓
# Optical Flow
#   ↓
# Density
#   ↓
# Normal Behaviour Baseline
#   ↓
# Risk Score
#   ↓
# NORMAL / ABNORMAL / HIGH_RISK
#   ↓
# Persistent High Risk
#   ↓
# Event Grouping
#   ↓
# Confirmed Stampede Events JSON + Complete Analysis JSON
#
# Every execution creates a NEW timestamped output folder.
#
# CHANGELOG (V3.3 -> V3.4):
#   - Stampede Detection consumes the ordered frame metadata generated by
#     the video-input entry point.
#   - Event grouping produces one structured event record per detected
#     abnormal event, including WARNING and CRITICAL events.
#   - "stampede_events.json" contains confirmed stampede events only.
#   - "stampede_output.json" contains the complete analysis summary and
#     all grouped events.
#   - camera_id / zone_id resolution is explicit and documented.
#
# ============================================================


# ============================================================
# CONFIGURATION
# ============================================================

@dataclass
class StampedeConfig:

    # Minimum number of frames a tracking ID must appear in.
    min_track_length: int = 15

    # Smoothing window.
    smoothing_window: int = 7

    # First part of the video used as normal baseline.
    baseline_seconds: float = 10.0

    # Baseline safety safeguard. Frames where 20% or more of
    # tracked people are moving rapidly are excluded from the
    # normal-behaviour baseline.
    baseline_running_ratio_threshold: float = 0.20

    # Optical-flow threshold.
    flow_magnitude_threshold: float = 0.5

    # Motion entropy bins.
    entropy_bins: int = 36

    # Rapid movement detection.
    rapid_motion_multiplier: float = 1.5
    minimum_rapid_speed: float = 15.0

    # Behaviour states.
    abnormal_threshold: float = 0.55
    high_risk_threshold: float = 0.70

    # High-risk persistence.
    persistence_seconds: float = 1.5

    # Minimum event duration.
    minimum_abnormal_duration: float = 0.30

    # Maximum gap between abnormal frames in one event.
    event_gap_seconds: float = 1.0


# ============================================================
# DETECTOR
# ============================================================

class StampedeDetector:

    def __init__(
        self,
        fps: float,
        config: Optional[StampedeConfig] = None,
    ):

        if fps <= 0:
            raise ValueError(
                "FPS must be greater than zero."
            )

        self.fps = float(fps)

        self.config = (
            config
            if config is not None
            else StampedeConfig()
        )

        self.previous_gray = None

        self.baseline = None

    # ========================================================
    # SPEED
    # ========================================================

    def calculate_speed(
        self,
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        df = tracking_data.copy()

        df = df.sort_values(
            ["track_id", "frame"]
        )

        dx = (
            df.groupby("track_id")["x"]
            .diff()
        )

        dy = (
            df.groupby("track_id")["y"]
            .diff()
        )

        distance = np.sqrt(
            dx ** 2 +
            dy ** 2
        )

        df["displacement"] = (
            distance.fillna(0.0)
        )

        df["speed"] = (
            df["displacement"]
            * self.fps
        )

        return df

    # ========================================================
    # ACCELERATION
    # ========================================================

    def calculate_acceleration(
        self,
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        df = tracking_data.copy()

        df = df.sort_values(
            ["track_id", "frame"]
        )

        df["acceleration"] = (
            df.groupby("track_id")["speed"]
            .diff()
            .fillna(0.0)
            * self.fps
        )

        df["acceleration"] = (
            df["acceleration"]
            .abs()
        )

        window = (
            self.config.smoothing_window
        )

        df["acceleration_smoothed"] = (
            df.groupby("track_id")[
                "acceleration"
            ]
            .transform(
                lambda x:
                x.rolling(
                    window=window,
                    min_periods=1,
                    center=True,
                ).median()
            )
        )

        return df

    # ========================================================
    # DIRECTION
    # ========================================================

    def calculate_direction(
        self,
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        df = tracking_data.copy()

        df = df.sort_values(
            ["track_id", "frame"]
        )

        dx = (
            df.groupby("track_id")["x"]
            .diff()
        )

        dy = (
            df.groupby("track_id")["y"]
            .diff()
        )

        df["direction_degrees"] = (
            np.degrees(
                np.arctan2(
                    dy,
                    dx,
                )
            )
        )

        return df

    # ========================================================
    # RAPID MOTION
    # ========================================================

    def calculate_rapid_motion(
        self,
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        df = tracking_data.copy()

        valid_speed = (
            df["speed"]
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
            .dropna()
        )

        if valid_speed.empty:

            reference = 0.0

        else:

            reference = float(
                valid_speed.quantile(0.75)
            )

        threshold = max(
            reference
            * self.config.rapid_motion_multiplier,
            self.config.minimum_rapid_speed,
        )

        df[
            "rapid_motion_threshold"
        ] = threshold

        df[
            "rapid_motion"
        ] = (
            df["speed"]
            > threshold
        )

        print(
            f"Rapid-motion threshold: "
            f"{threshold:.2f} px/s"
        )

        return df

    # ========================================================
    # DENSITY
    # ========================================================

    def calculate_density(
        self,
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        density = (
            tracking_data
            .groupby("frame")["track_id"]
            .nunique()
            .rename("head_count_density")
            .reset_index()
        )

        density[
            "density_change"
        ] = (
            density[
                "head_count_density"
            ]
            .diff()
            .fillna(0.0)
        )

        density[
            "density_change_smoothed"
        ] = (
            density[
                "density_change"
            ]
            .rolling(
                window=self.config.smoothing_window,
                min_periods=1,
                center=True,
            )
            .median()
            .fillna(0.0)
        )

        return density[
            [
                "frame",
                "head_count_density",
                "density_change",
                "density_change_smoothed",
            ]
        ]

    # ========================================================
    # DIRECTION CONSISTENCY
    # ========================================================

    @staticmethod
    def calculate_direction_consistency(
        tracking_data: pd.DataFrame,
    ) -> pd.DataFrame:

        rows = []

        for frame_id, group in (
            tracking_data.groupby("frame")
        ):

            directions = (
                group[
                    "direction_degrees"
                ]
                .dropna()
                .values
            )

            if len(directions) == 0:

                consistency = 0.0

            else:

                radians = np.radians(
                    directions
                )

                mean_x = np.mean(
                    np.cos(radians)
                )

                mean_y = np.mean(
                    np.sin(radians)
                )

                consistency = float(
                    np.sqrt(
                        mean_x ** 2
                        +
                        mean_y ** 2
                    )
                )

            rows.append(
                {
                    "frame":
                        int(frame_id),

                    "direction_consistency":
                        consistency,
                }
            )

        return pd.DataFrame(
            rows
        )

    # ========================================================
    # OPTICAL FLOW
    # ========================================================

    def calculate_optical_flow(
        self,
        frame: Optional[np.ndarray],
    ) -> dict:

        empty = {

            "optical_flow_magnitude":
                0.0,

            "optical_flow_p95":
                0.0,

            "flow_divergence":
                0.0,

            "motion_entropy":
                0.0,

            "optical_flow_direction":
                0.0,
        }

        if frame is None:

            return empty

        gray = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2GRAY,
        )

        if self.previous_gray is None:

            self.previous_gray = gray

            return empty

        flow = cv2.calcOpticalFlowFarneback(

            self.previous_gray,
            gray,

            None,

            0.5,
            3,
            15,
            3,
            5,
            1.2,
            0,
        )

        u = flow[..., 0]

        v = flow[..., 1]

        magnitude = np.sqrt(
            u ** 2 +
            v ** 2
        )

        angle = np.arctan2(
            v,
            u,
        )

        valid = (
            magnitude
            >
            self.config.flow_magnitude_threshold
        )

        if not np.any(valid):

            self.previous_gray = gray

            return empty

        valid_magnitude = (
            magnitude[valid]
        )

        mean_magnitude = float(
            np.mean(
                valid_magnitude
            )
        )

        p95_magnitude = float(
            np.percentile(
                valid_magnitude,
                95,
            )
        )

        # ----------------------------------------------------
        # FLOW DIVERGENCE
        # ----------------------------------------------------

        du_dx = np.gradient(
            u,
            axis=1,
        )

        dv_dy = np.gradient(
            v,
            axis=0,
        )

        divergence = (
            du_dx +
            dv_dy
        )

        mean_divergence = float(
            np.mean(
                np.abs(
                    divergence[valid]
                )
            )
        )

        # ----------------------------------------------------
        # MOTION ENTROPY
        # ----------------------------------------------------

        histogram, _ = np.histogram(

            angle[valid],

            bins=self.config.entropy_bins,

            range=(
                -np.pi,
                np.pi,
            ),
        )

        if histogram.sum() > 0:

            probabilities = (
                histogram
                /
                histogram.sum()
            )

            probabilities = (
                probabilities[
                    probabilities > 0
                ]
            )

            entropy = float(
                -np.sum(
                    probabilities
                    *
                    np.log(
                        probabilities
                    )
                )
            )

        else:

            entropy = 0.0

        # ----------------------------------------------------
        # AVERAGE FLOW DIRECTION
        # ----------------------------------------------------

        mean_u = float(
            np.mean(
                u[valid]
            )
        )

        mean_v = float(
            np.mean(
                v[valid]
            )
        )

        direction = float(
            np.degrees(
                np.arctan2(
                    mean_v,
                    mean_u,
                )
            )
        )

        self.previous_gray = gray

        return {

            "optical_flow_magnitude":
                mean_magnitude,

            "optical_flow_p95":
                p95_magnitude,

            "flow_divergence":
                mean_divergence,

            "motion_entropy":
                entropy,

            "optical_flow_direction":
                direction,
        }

    # ========================================================
    # BASELINE
    # ========================================================

    def establish_baseline(
        self,
        features: pd.DataFrame,
    ) -> Dict:

        baseline_frames = int(
            self.config.baseline_seconds
            * self.fps
        )

        # Initial baseline window.
        baseline_window = features[
            features["frame"]
            < baseline_frames
        ].copy()

        # 20% running-ratio safeguard. Frames where 20% or more
        # of tracked people are moving rapidly are excluded from
        # the normal-behaviour baseline.
        running_threshold = (
            self.config.baseline_running_ratio_threshold
        )

        if "rapid_motion_ratio" in baseline_window.columns:
            safe_baseline = baseline_window[
                baseline_window["rapid_motion_ratio"]
                < running_threshold
            ].copy()
        else:
            safe_baseline = baseline_window.copy()

        # Use the safeguarded baseline when enough normal frames
        # remain. Otherwise retain the original baseline window.
        if len(safe_baseline) >= 10:
            baseline = safe_baseline
        else:
            baseline = baseline_window

        excluded_frames = (
            len(baseline_window)
            - len(safe_baseline)
        )

        if excluded_frames > 0:
            print(
                f"Baseline safeguard: excluded "
                f"{excluded_frames} frames where rapid-motion "
                f"ratio was >= {running_threshold:.0%}."
            )

        # Final fallback if the baseline is still too small.
        if len(baseline) < 10:
            baseline = features.head(
                min(
                    300,
                    len(features),
                )
            )

        columns = [

            "avg_speed",

            "avg_acceleration",

            "rapid_motion_ratio",

            "optical_flow_magnitude",

            "optical_flow_p95",

            "flow_divergence",

            "motion_entropy",

            "density_change_smoothed",
        ]

        stats = {}

        for column in columns:

            if column not in baseline.columns:

                continue

            values = (
                baseline[column]
                .replace(
                    [np.inf, -np.inf],
                    np.nan,
                )
                .fillna(0.0)
            )

            mean = float(
                values.mean()
            )

            std = float(
                values.std()
            )

            if std < 1e-6:

                std = 1e-6

            stats[column] = {

                "mean":
                    mean,

                "std":
                    std,
            }

        self.baseline = stats

        return stats

    # ========================================================
    # POSITIVE Z SCORE
    # ========================================================

    def positive_zscore(
        self,
        value: float,
        feature_name: str,
    ) -> float:

        if (
            self.baseline is None
            or
            feature_name
            not in self.baseline
        ):

            return 0.0

        mean = (
            self.baseline[
                feature_name
            ]["mean"]
        )

        std = (
            self.baseline[
                feature_name
            ]["std"]
        )

        z = (
            value - mean
        ) / std

        return float(
            max(
                0.0,
                z,
            )
        )

    # ========================================================
    # SUDDEN MOTION CHANGE
    # ========================================================

    def calculate_sudden_change(
        self,
        features: pd.DataFrame,
    ) -> pd.Series:

        columns = [

            "avg_speed",

            "avg_acceleration",

            "optical_flow_magnitude",

            "optical_flow_p95",

            "rapid_motion_ratio",
        ]

        available = [

            column

            for column in columns

            if column in features.columns
        ]

        if not available:

            return pd.Series(
                0.0,
                index=features.index,
            )

        changes = []

        lookback = max(
            5,
            int(
                self.fps
                * 0.5
            ),
        )

        for column in available:

            current = (
                features[column]
                .astype(float)
            )

            previous = (
                current.shift(
                    lookback
                )
            )

            change = (
                current -
                previous
            )

            baseline = (
                self.baseline.get(
                    column,
                    {
                        "mean": 0.0,
                        "std": 1.0,
                    },
                )
            )

            std = max(
                baseline["std"],
                1e-6,
            )

            z = (
                change /
                std
            )

            changes.append(
                z.clip(
                    lower=0
                )
            )

        result = (
            pd.concat(
                changes,
                axis=1,
            )
            .mean(axis=1)
        )

        return result.clip(
            lower=0,
            upper=4,
        )

    # ========================================================
    # RISK SCORE
    # ========================================================

    def calculate_anomaly_score(
        self,
        row: pd.Series,
    ) -> float:

        speed = np.clip(

            self.positive_zscore(
                float(
                    row["avg_speed"]
                ),
                "avg_speed",
            )
            / 3.0,

            0,
            1,
        )

        acceleration = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "avg_acceleration"
                    ]
                ),
                "avg_acceleration",
            )
            / 3.0,

            0,
            1,
        )

        rapid = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "rapid_motion_ratio"
                    ]
                ),
                "rapid_motion_ratio",
            )
            / 2.5,

            0,
            1,
        )

        flow = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "optical_flow_magnitude"
                    ]
                ),
                "optical_flow_magnitude",
            )
            / 3.0,

            0,
            1,
        )

        flow_p95 = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "optical_flow_p95"
                    ]
                ),
                "optical_flow_p95",
            )
            / 3.0,

            0,
            1,
        )

        divergence = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "flow_divergence"
                    ]
                ),
                "flow_divergence",
            )
            / 3.0,

            0,
            1,
        )

        entropy = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "motion_entropy"
                    ]
                ),
                "motion_entropy",
            )
            / 3.0,

            0,
            1,
        )

        density = np.clip(

            self.positive_zscore(
                float(
                    row[
                        "density_change_smoothed"
                    ]
                ),
                "density_change_smoothed",
            )
            / 3.0,

            0,
            1,
        )

        sudden = np.clip(

            float(
                row.get(
                    "sudden_motion_change",
                    0.0,
                )
            )
            / 3.0,

            0,
            1,
        )

        # ----------------------------------------------------
        # FINAL WEIGHTED SCORE
        # ----------------------------------------------------

        score = (

            0.17 * speed

            + 0.08 * acceleration

            + 0.16 * rapid

            + 0.20 * flow

            + 0.09 * flow_p95

            + 0.08 * divergence

            + 0.07 * entropy

            + 0.05 * density

            + 0.10 * sudden
        )

        # ----------------------------------------------------
        # MULTI-SIGNAL AGREEMENT
        # ----------------------------------------------------

        signals = [

            speed,

            acceleration,

            rapid,

            flow,

            flow_p95,

            divergence,

            entropy,

            density,

            sudden,
        ]

        strong_signals = sum(
            value >= 0.55
            for value in signals
        )

        if strong_signals >= 5:

            score += 0.10

        elif strong_signals >= 4:

            score += 0.07

        elif strong_signals >= 3:

            score += 0.03

        return float(
            np.clip(
                score,
                0.0,
                1.0,
            )
        )

    # ========================================================
    # THREE-STATE CLASSIFICATION
    # ========================================================

    def classify_state(
        self,
        score: float,
    ) -> str:

        if (
            score
            >=
            self.config.high_risk_threshold
        ):

            return "HIGH_RISK"

        if (
            score
            >=
            self.config.abnormal_threshold
        ):

            return "ABNORMAL"

        return "NORMAL"


# ============================================================
# NEW RUN FOLDER
# ============================================================

def create_run_directory(
    output_root: str,
) -> Path:

    root = Path(
        output_root
    )

    root.mkdir(
        parents=True,
        exist_ok=True,
    )

    timestamp = datetime.now().strftime(
        "run_%Y%m%d_%H%M%S"
    )

    run_dir = (
        root /
        timestamp
    )

    counter = 1

    while run_dir.exists():

        run_dir = (
            root /
            f"{timestamp}_{counter:02d}"
        )

        counter += 1

    run_dir.mkdir(
        parents=True
    )

    return run_dir


# ============================================================
# MOVEMENT DIRECTION
# ============================================================

def direction_to_compass(
    degrees: float,
) -> str:

    directions = [

        "EAST",

        "NORTH-EAST",

        "NORTH",

        "NORTH-WEST",

        "WEST",

        "SOUTH-WEST",

        "SOUTH",

        "SOUTH-EAST",
    ]

    index = int(
        (
            (degrees % 360)
            + 22.5
        )
        // 45
    ) % 8

    return directions[index]


# ============================================================
# CAMERA / ZONE RESOLUTION
# ============================================================

def resolve_camera_and_zone(
    input_data: dict,
    camera_id_override: Optional[str] = None,
    zone_id_override: Optional[str] = None,
) -> tuple[str, str]:
    """Resolve camera_id / zone_id for this run.

    IMPORTANT: The Video Processing -> Crowd Detection contract
    (section 1 of the API doc) does not define camera_id or zone_id
    anywhere in its JSON schema, at the top level or per-frame. The
    Stampede Detection contract (section 4) requires both fields on
    every detection object, so they must be supplied from somewhere
    outside that schema until the contract is updated.

    Resolution order (first match wins):
      1. Explicit CLI / function override.
      2. Top-level "camera_id" / "zone_id" keys on the input JSON,
         if some upstream stage has started adding them.
      3. Empty string, with a loud warning, so the pipeline does not
         silently produce misleading data.
    """

    camera_id = (
        camera_id_override
        or input_data.get("camera_id")
        or ""
    )

    zone_id = (
        zone_id_override
        or input_data.get("zone_id")
        or ""
    )

    if not camera_id or not zone_id:
        print(
            "[WARN] camera_id/zone_id could not be resolved from "
            "the Video Processing input or CLI overrides. The "
            "current Video Processing contract does not define "
            "these fields. Detections will be emitted with "
            f"camera_id={camera_id!r} zone_id={zone_id!r}. Pass "
            "--camera-id/--zone-id or update the upstream contract "
            "to fix this."
        )

    return camera_id, zone_id


# ============================================================
# LEGACY PER-FRAME DETECTION BUILDER (not written to final JSON outputs)
# ============================================================

def build_stampede_detections(
    features: pd.DataFrame,
    camera_id: str,
    zone_id: str,
):
    """Build per-frame detections for legacy callers.

    The final team outputs are event-level JSON files produced by
    ``analyse_video``; this helper is retained for compatibility.
    """

    detections = []

    for _, row in features.iterrows():

        confirmed_stampede = bool(
            row.get("persistent_high_risk", False)
        )

        severity = (
            "CRITICAL"
            if confirmed_stampede
            else "NONE"
        )

        direction = direction_to_compass(
            float(row.get("optical_flow_direction", 0.0))
        )

        detections.append(
            {
                "frame_id": int(row["frame"]),

                "timestamp": round(
                    float(row["timestamp"]), 3
                ),

                "camera_id": camera_id,

                "zone_id": zone_id,

                "stampede_detected": confirmed_stampede,

                "confidence": round(
                    float(row.get("risk_score_smoothed", 0.0)), 3
                ),

                "severity": severity,

                "crowd_count": int(row.get("head_count", 0)),

                "movement_direction": direction,

                "movement_speed": round(
                    float(row.get("avg_speed", 0.0)), 3
                ),

                "abnormal_movement": bool(
                    row.get("state", "NORMAL") != "NORMAL"
                ),
            }
        )

    return detections


# ============================================================
# BUILD INTERNAL EVENT SUMMARIES (grouped, richer states)
# ============================================================

def build_event_summaries(
    features: pd.DataFrame,
    video_id: str,
    camera_id: str,
    zone_id: str,
):
    """Group contiguous abnormal frames into event-level output.

    Every grouped abnormal event is returned, including WARNING and
    CRITICAL events. Confirmed stampede events are identified by
    ``stampede_detected=True``; event-level movement direction and
    timing information are retained for both severities.
    """

    event_rows = features[
        features["event_id"] > 0
    ]

    events = []

    for event_id, group in (
        event_rows.groupby(
            "event_id"
        )
    ):

        peak_index = (
            group[
                "risk_score_smoothed"
            ]
            .idxmax()
        )

        peak = features.loc[
            peak_index
        ]

        # Confirmed stampede only when
        # high-risk behaviour persisted.
        stampede_detected = bool(
            group[
                "persistent_high_risk"
            ]
            .astype(bool)
            .any()
        )

        if stampede_detected:

            severity = "CRITICAL"

        else:

            # Internal-only concept: an abnormal-but-not-confirmed
            # event. Never surfaced on the team-facing contract.
            severity = "WARNING"

        start_time = float(
            group[
                "timestamp"
            ].min()
        )

        end_time = float(
            group[
                "timestamp"
            ].max()
        )

        max_crowd = int(
            group[
                "head_count"
            ]
            .max()
        )

        max_speed = float(
            group[
                "avg_speed"
            ]
            .max()
        )

        direction = (
            direction_to_compass(
                float(
                    peak[
                        "optical_flow_direction"
                    ]
                )
            )
        )

        events.append(
            {

                "event_id":
                    int(event_id),

                "frame_id":
                    int(
                        peak["frame"]
                    ),

                "timestamp":
                    round(
                        float(
                            peak[
                                "timestamp"
                            ]
                        ),
                        3,
                    ),

                "camera_id":
                    camera_id,

                "zone_id":
                    zone_id,

                "stampede_detected":
                    stampede_detected,

                "confidence":
                    round(
                        float(
                            peak[
                                "risk_score_smoothed"
                            ]
                        ),
                        3,
                    ),

                "severity":
                    severity,

                "crowd_count":
                    max_crowd,

                "movement_direction":
                    direction,

                "movement_speed":
                    round(
                        max_speed,
                        3,
                    ),

                "abnormal_movement":
                    True,

                "event_start":
                    round(
                        start_time,
                        3,
                    ),

                "event_end":
                    round(
                        end_time,
                        3,
                    ),

                "event_duration":
                    round(
                        end_time -
                        start_time,
                        3,
                    ),

                "frames_in_event":
                    int(
                        len(group)
                    ),
            }
        )

    return events


# ============================================================
# MAIN VIDEO ANALYSIS
# ============================================================

def prepare_pipeline_frames(input_data: dict):
    """Prepare consecutive frame metadata for Stampede Detection.

    The Stampede Detection entry point provides video_id and ordered
    frames containing frame_id, timestamp, and frame_path. The frames
    are generated directly from the input video before this helper
    is called.

    This helper resolves frame paths, derives FPS from timestamps,
    and reads the first valid frame to determine resolution.
    """
    frames = input_data.get("frames", [])

    if not frames:
        raise ValueError(
            "Stampede Detection requires a non-empty 'frames' list."
        )

    prepared_frames = []

    for frame_data in frames:
        frame_id = frame_data.get("frame_id")
        timestamp = frame_data.get("timestamp")
        frame_path = frame_data.get("frame_path")

        if frame_id is None or timestamp is None or not frame_path:
            continue

        resolved_path = Path(frame_path)

        if not resolved_path.is_absolute():
            resolved_path = Path(__file__).resolve().parent.parent / resolved_path

        prepared_frames.append(
            {
                "frame_id": int(frame_id),
                "timestamp": float(timestamp),
                "frame_path": str(resolved_path),
            }
        )

    if not prepared_frames:
        raise ValueError(
            "No valid frames were found in the pipeline input."
        )

    prepared_frames.sort(key=lambda item: item["frame_id"])

    fps = 0.0

    if len(prepared_frames) >= 2:
        time_differences = []

        for previous, current in zip(
            prepared_frames,
            prepared_frames[1:],
        ):
            delta = current["timestamp"] - previous["timestamp"]

            if delta > 0:
                time_differences.append(delta)

        if time_differences:
            median_delta = float(np.median(time_differences))
            fps = 1.0 / median_delta

    if fps <= 0:
        raise ValueError(
            "Could not derive a valid FPS from pipeline frame timestamps."
        )

    width = 0
    height = 0

    for frame_data in prepared_frames:
        frame = cv2.imread(frame_data["frame_path"])

        if frame is not None:
            height, width = frame.shape[:2]
            break

    if width <= 0 or height <= 0:
        raise RuntimeError(
            "Could not read any pipeline frame to determine resolution."
        )

    return prepared_frames, fps, width, height


def analyse_video(
    input_data: dict,
    output_dir: Path,
    video_id: str,
    camera_id: str,
    zone_id: str,
):

    from ultralytics import YOLO

    from huggingface_hub import (
        hf_hub_download
    )

    # ========================================================
    # VIDEO INFORMATION
    # ========================================================

    prepared_frames, fps, width, height = prepare_pipeline_frames(
        input_data
    )

    total_frames = len(prepared_frames)

    duration = (
        prepared_frames[-1]["timestamp"]
        if prepared_frames
        else 0.0
    )

    print()
    print("=" * 70)
    print(
        "VIDEO INFORMATION"
    )
    print("=" * 70)

    print(
        f"Resolution : "
        f"{width} x {height}"
    )

    print(
        f"FPS        : "
        f"{fps:.2f}"
    )

    print(
        f"Frames     : "
        f"{total_frames}"
    )

    print(
        f"Duration   : "
        f"{duration:.2f} seconds"
    )

    # ========================================================
    # YOLO
    # ========================================================

    print()
    print("=" * 70)
    print(
        "LOADING YOLOv8 HEAD MODEL"
    )
    print("=" * 70)

    model_path = hf_hub_download(

        repo_id=(
            "AmineSam/"
            "irail-crowd-counting-yolov8n"
        ),

        filename="best.pt",
    )

    model = YOLO(
        model_path
    )

    print(
        "Model loaded."
    )

    print(
        "Classes:",
        model.names
    )

    # ========================================================
    # TRACKING
    # ========================================================

    print()
    print("=" * 70)
    print(
        "YOLOv8 + BoT-SORT TRACKING"
    )
    print("=" * 70)

    tracking_rows = []

    for frame_data in prepared_frames:

        frame = cv2.imread(
            frame_data["frame_path"]
        )

        if frame is None:
            print(
                f"[WARN] Could not read frame "
                f"{frame_data['frame_id']} — skipping"
            )
            continue

        results = model.track(

            source=frame,

            device=0,

            conf=0.30,

            imgsz=832,

            iou=0.75,

            tracker="botsort.yaml",

            persist=True,

            verbose=False,
        )

        result = results[0]

        if (
            result.boxes is None
            or
            result.boxes.id is None
        ):

            continue

        boxes = (
            result.boxes.xyxy
            .cpu()
            .numpy()
        )

        ids = (
            result.boxes.id
            .cpu()
            .numpy()
            .astype(int)
        )

        confidences = (
            result.boxes.conf
            .cpu()
            .numpy()
        )

        for (
            box,
            track_id,
            confidence,
        ) in zip(
            boxes,
            ids,
            confidences,
        ):

            x1, y1, x2, y2 = box

            cx = (
                x1 +
                x2
            ) / 2.0

            cy = (
                y1 +
                y2
            ) / 2.0

            tracking_rows.append(
                {

                    "frame":
                        frame_data["frame_id"],

                    "track_id":
                        int(
                            track_id
                        ),

                    "x":
                        float(cx),

                    "y":
                        float(cy),

                    "width":
                        float(
                            x2 -
                            x1
                        ),

                    "height":
                        float(
                            y2 -
                            y1
                        ),

                    "confidence":
                        float(
                            confidence
                        ),
                }
            )

    tracking_data = pd.DataFrame(
        tracking_rows
    )

    if tracking_data.empty:

        raise RuntimeError(
            "No tracking detections "
            "were produced."
        )

    print(
        f"Tracking records : "
        f"{len(tracking_data)}"
    )

    print(
        f"Unique track IDs : "
        f"{tracking_data['track_id'].nunique()}"
    )

    print(
        f"Frames tracked   : "
        f"{tracking_data['frame'].nunique()}"
    )

    # ========================================================
    # TRACK FILTERING
    # ========================================================

    config = StampedeConfig()

    lengths = (
        tracking_data
        .groupby("track_id")
        .size()
    )

    valid_ids = lengths[
        lengths
        >= config.min_track_length
    ].index

    tracking_data = (
        tracking_data[
            tracking_data[
                "track_id"
            ].isin(valid_ids)
        ]
        .copy()
    )

    print()
    print("=" * 70)
    print(
        "TRACK FILTERING"
    )
    print("=" * 70)

    print(
        f"Valid tracks    : "
        f"{tracking_data['track_id'].nunique()}"
    )

    # ========================================================
    # MOTION FEATURES
    # ========================================================

    detector = StampedeDetector(
        fps=fps,
        config=config,
    )

    tracking_data = (
        detector.calculate_speed(
            tracking_data
        )
    )

    tracking_data = (
        detector.calculate_acceleration(
            tracking_data
        )
    )

    tracking_data = (
        detector.calculate_direction(
            tracking_data
        )
    )

    tracking_data = (
        detector.calculate_rapid_motion(
            tracking_data
        )
    )

    density = (
        detector.calculate_density(
            tracking_data
        )
    )

    consistency = (
        detector.calculate_direction_consistency(
            tracking_data
        )
    )

    # ========================================================
    # FRAME FEATURES
    # ========================================================

    frame_features = (

        tracking_data

        .groupby("frame")

        .agg(

            head_count=(
                "track_id",
                "nunique",
            ),

            avg_speed=(
                "speed",
                "mean",
            ),

            avg_acceleration=(
                "acceleration_smoothed",
                "mean",
            ),

            rapid_people=(
                "rapid_motion",
                "sum",
            ),
        )

        .reset_index()
    )

    frame_features[
        "rapid_motion_ratio"
    ] = (

        frame_features[
            "rapid_people"
        ]

        /

        frame_features[
            "head_count"
        ].replace(
            0,
            np.nan,
        )
    )

    # IMPORTANT:
    #
    # Density has its own head-count column.
    # We only merge density-change values.
    #
    # This prevents the previous
    # KeyError/head_count collision.

    density_for_merge = density[
        [
            "frame",
            "density_change",
            "density_change_smoothed",
        ]
    ]

    frame_features = (
        frame_features

        .merge(
            density_for_merge,
            on="frame",
            how="left",
        )

        .merge(
            consistency,
            on="frame",
            how="left",
        )
    )

    frame_features = (
        frame_features

        .replace(
            [np.inf, -np.inf],
            np.nan,
        )

        .fillna(0.0)
    )

    # ========================================================
    # OPTICAL FLOW
    # ========================================================

    print()
    print("=" * 70)
    print(
        "STREAMING FARNEBACK OPTICAL FLOW"
    )
    print("=" * 70)

    flow_detector = StampedeDetector(
        fps=fps,
        config=config,
    )

    flow_rows = []

    for frame_data in prepared_frames:

        frame = cv2.imread(
            frame_data["frame_path"]
        )

        if frame is None:
            print(
                f"[WARN] Could not read frame "
                f"{frame_data['frame_id']} — skipping"
            )
            continue

        flow = (
            flow_detector
            .calculate_optical_flow(
                frame
            )
        )

        flow_rows.append(
            {

                "frame":
                    frame_data["frame_id"],

                "optical_flow_magnitude":
                    flow[
                        "optical_flow_magnitude"
                    ],

                "optical_flow_p95":
                    flow[
                        "optical_flow_p95"
                    ],

                "flow_divergence":
                    flow[
                        "flow_divergence"
                    ],

                "motion_entropy":
                    flow[
                        "motion_entropy"
                    ],

                "optical_flow_direction":
                    flow[
                        "optical_flow_direction"
                    ],
            }
        )

    flow_data = pd.DataFrame(
        flow_rows
    )

    print(
        f"Optical-flow frames: "
        f"{len(flow_data)}"
    )

    # ========================================================
    # COMBINE
    # ========================================================

    features = (

        frame_features

        .merge(
            flow_data,
            on="frame",
            how="outer",
        )

        .sort_values(
            "frame"
        )

        .reset_index(
            drop=True
        )
    )

    features[
        "timestamp"
    ] = (

        features[
            "frame"
        ]

        /

        fps
    )

    features = (
        features

        .replace(
            [np.inf, -np.inf],
            np.nan,
        )

        .fillna(0.0)
    )

    # ========================================================
    # NORMAL BASELINE
    # ========================================================

    print()
    print("=" * 70)
    print(
        "NORMAL BEHAVIOUR BASELINE"
    )
    print("=" * 70)

    detector.establish_baseline(
        features
    )

    for (
        name,
        values,
    ) in detector.baseline.items():

        print(
            f"{name:30s} "
            f"mean={values['mean']:.4f} "
            f"std={values['std']:.4f}"
        )

    # ========================================================
    # SUDDEN MOTION
    # ========================================================

    features[
        "sudden_motion_change"
    ] = (

        detector.calculate_sudden_change(
            features
        )
    )

    # ========================================================
    # RISK SCORE
    # ========================================================

    scores = []

    for _, row in features.iterrows():

        scores.append(
            detector.calculate_anomaly_score(
                row
            )
        )

    features[
        "risk_score"
    ] = scores

    # ========================================================
    # RISK SMOOTHING
    # ========================================================

    smoothing_frames = max(

        3,

        int(
            fps
            *
            config.smoothing_window
            /
            2
        ),
    )

    features[
        "risk_score_smoothed"
    ] = (

        features[
            "risk_score"
        ]

        .rolling(
            window=smoothing_frames,
            min_periods=1,
            center=True,
        )

        .median()

        .bfill()

        .ffill()
    )

    # ========================================================
    # THREE STATES
    # ========================================================

    features[
        "state"
    ] = (

        features[
            "risk_score_smoothed"
        ]

        .apply(
            detector.classify_state
        )
    )

    # Compatibility column.
    features[
        "status"
    ] = features[
        "state"
    ]

    # ========================================================
    # PERSISTENT HIGH RISK
    # ========================================================

    persistence_frames = max(

        1,

        int(
            config.persistence_seconds
            * fps
        ),
    )

    high = (

        features[
            "risk_score_smoothed"
        ]

        >=

        config.high_risk_threshold
    )

    group_id = (
        (~high)
        .cumsum()
    )

    consecutive_high = (

        high.astype(int)

        .groupby(
            group_id
        )

        .cumsum()
    )

    features[
        "persistent_high_risk"
    ] = (

        consecutive_high

        >=

        persistence_frames
    )

    # ========================================================
    # ABNORMAL EVENTS (internal grouping)
    # ========================================================

    abnormal = (

        features[
            "state"
        ]

        !=

        "NORMAL"
    )

    gap_frames = max(

        1,

        int(
            config.event_gap_seconds
            * fps
        ),
    )

    event_ids = np.zeros(

        len(features),

        dtype=int,
    )

    event_number = 0

    last_abnormal_index = None

    for (
        i,
        is_abnormal,
    ) in enumerate(
        abnormal.values
    ):

        if is_abnormal:

            if (

                last_abnormal_index
                is None

                or

                i -
                last_abnormal_index
                >
                gap_frames
            ):

                event_number += 1

            event_ids[i] = (
                event_number
            )

            last_abnormal_index = i

    features[
        "event_id"
    ] = event_ids

    # ========================================================
    # REMOVE VERY SHORT EVENTS
    # ========================================================

    minimum_event_frames = max(

        1,

        int(
            config.minimum_abnormal_duration
            * fps
        ),
    )

    for event_id in sorted(
        set(event_ids)
    ):

        if event_id == 0:

            continue

        count = int(

            (
                features[
                    "event_id"
                ]

                ==

                event_id
            )

            .sum()
        )

        if (
            count
            <
            minimum_event_frames
        ):

            features.loc[

                features[
                    "event_id"
                ]

                ==

                event_id,

                "event_id",
            ] = 0

    # ========================================================
    # RE-NUMBER EVENTS
    # ========================================================

    mapping = {}

    current = 0

    for event_id in sorted(
        set(
            features[
                "event_id"
            ]
        )
    ):

        if event_id == 0:

            continue

        current += 1

        mapping[
            event_id
        ] = current

    features[
        "event_id"
    ] = (

        features[
            "event_id"
        ]

        .map(
            lambda x:
            mapping.get(
                x,
                0,
            )
        )
    )

    # ========================================================
    # BUILD EVENT SUMMARIES
    # ========================================================

    events = build_event_summaries(

        features,

        video_id,

        camera_id,

        zone_id,
    )

    # Build a complete per-frame output for every frame, including NORMAL frames.
    detections = build_stampede_detections(

        features,

        camera_id,

        zone_id,
    )

    # ========================================================
    # FINAL JSON OUTPUTS
    # ========================================================

    confirmed_events = [
        event
        for event in events
        if event["stampede_detected"]
    ]

    events_path = (
        output_dir /
        "stampede_events.json"
    )

    confirmed_events_json = {

        "video_id":
            video_id,

        "events":
            confirmed_events,
    }

    with open(
        events_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            confirmed_events_json,
            file,
            indent=4,
        )

    output_path = (
        output_dir /
        "stampede_output.json"
    )

    complete_output = {

        "video_id":
            video_id,

        "camera_id":
            camera_id,

        "zone_id":
            zone_id,

        "frame_source":
            "video_input",

        "detector_version":
            "V3.4",

        # Complete per-frame analysis output, including NORMAL frames.
        "total_detections":
            len(detections),

        "detections":
            detections,

        # Grouped abnormal-event summaries (WARNING + CRITICAL).
        "events":
            events,
    }

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            complete_output,
            file,
            indent=4,
        )

    # ========================================================
    # OUTPUT INFORMATION
    # ========================================================

    print()
    print("=" * 70)
    print("FINAL OUTPUTS")
    print("=" * 70)

    print(
        f"Stampede events : {events_path}"
    )

    print(
        f"Full output     : {output_path}"
    )

    print()
    print(
        "STAMPEDE DETECTION COMPLETE"
    )

    print("=" * 70)

    return features, events


# ============================================================
# MAIN
# ============================================================

def main():
    """Run Stampede Detection from Video Processing JSON metadata."""

    import argparse
    import json

    parser = argparse.ArgumentParser(
        description="Run Stampede Detection from pipeline frame metadata."
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Path to Video Processing JSON metadata.",
    )

    parser.add_argument(
        "--output-root",
        default="stampede_detection/data/output/stampede_runs",
        help="Root directory for stampede detection outputs.",
    )

    parser.add_argument(
        "--camera-id",
        default=None,
        help=(
            "Override camera_id. Not part of the current Video "
            "Processing contract -- required until that contract "
            "adds it."
        ),
    )

    parser.add_argument(
        "--zone-id",
        default=None,
        help=(
            "Override zone_id. Not part of the current Video "
            "Processing contract -- required until that contract "
            "adds it."
        ),
    )

    args = parser.parse_args()

    input_path = Path(args.input).expanduser()

    if not input_path.exists():
        raise FileNotFoundError(
            "Pipeline input JSON not found:\n"
            + str(input_path)
        )

    with input_path.open("r", encoding="utf-8") as file:
        input_data = json.load(file)

    video_id = input_data.get("video_id")

    if not video_id:
        raise ValueError(
            "Pipeline input requires 'video_id'."
        )

    if not input_data.get("frames"):
        raise ValueError(
            "Pipeline input requires a non-empty 'frames' list."
        )

    camera_id, zone_id = resolve_camera_and_zone(
        input_data,
        camera_id_override=args.camera_id,
        zone_id_override=args.zone_id,
    )

    run_dir = (
        Path(args.output_root)
        / str(video_id)
    )

    run_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()
    print("=" * 70)
    print("STAMPEDE DETECTION PIPELINE RUN")
    print("=" * 70)

    print(f"Video ID  : {video_id}")
    print(f"Camera ID : {camera_id}")
    print(f"Zone ID   : {zone_id}")
    print(f"Frames    : {len(input_data['frames'])}")
    print(f"Output    : {run_dir}")

    features, events = analyse_video(
        input_data=input_data,
        output_dir=run_dir,
        video_id=video_id,
        camera_id=camera_id,
        zone_id=zone_id,
    )

    result = {
        "video_id": video_id,
        "events": events,
    }

    print()
    print("Pipeline result:")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()